#!/bin/bash
# Make a gif using ImageMagick
#convert -set delay 50 -dispose 1 -loop 0 -scale 50% *.png Output.gif

# Make a mp4 using ffmpeg
ffmpeg -r 1/5 -i *.png -c:v libx264 -r 30 -pix_fmt yuv420p Output.mp4

# Make an mpeg -- not sure if it works
#convert -set delay 50 -quality 100  *.png Output.mpeg
